version: "3"
services:

  mariadb:
    image: ${MARIA_DB_IMAGE}
    container_name: slgi-emr-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./mariadb/sql:/docker-entrypoint-initdb.d/
      - ./mariadb/data:/var/lib/mysql

  redis:
    image: ${REDIS_IMAGE}
    container_name: slgi-emr-redis
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  backend:
    build:
      context: ./server
    image: ${USERNAME}/slgi-emr-backend
    environment:
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USER: ${SPRING_DATASOURCE_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}

    depends_on:
      - redis
      - mariadb

  frontend:
    build: 
      context: ./frontend
    image: ${USERNAME}/slgi-emr-frontend
    ports:
      - ${FRONTEND_PORT}
    depends_on:
      - backend
