version: "3"
services:

  mariadb:
    image: ${MARIA_DB_IMAGE}
    container_name: slgi-emr-mariadb
    env_file:
      .env
    volumes:
      - /home/ubuntu/sql:/docker-entrypoint-initdb.d/
      - /home/ubuntu/mariadb/data:/var/lib/mysql
      - /home/ubuntu/procedure:/var/run/procedure
    restart: always

  redis:
    image: ${REDIS_IMAGE}
    container_name: slgi-emr-redis
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    restart: always

  backend:
    build:
      context: ./server
    image: ${USERNAME}/slgi-emr-backend
    container_name: slgi-emr-backend
    env_file:
      .env
    depends_on:
      - redis
      - mariadb
    restart: always

  frontend:
    build: 
      context: ./frontend
    image: ${USERNAME}/slgi-emr-frontend
    container_name: slgi-emr-frontend
    ports:
      - ${FRONTEND_PORT}
    depends_on:
      - backend
    restart: always
